# the Docker Compose file
# first run docker daemon, the run the docker file in pycharm IDE
services:
  neo4j:
    container_name: neo4j
    restart: always
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/conf:/conf
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/Xyz0531!!